Fix: DynamoDB Typeerror with AWS Bedrock
Chainlit/chainlit pull request #1163
Opened 2024-07-25 08:51 UTC by munday-tech

When using AWS Bedrock, `_update_item` throws a TypeError as AWS Bedrock returns floats in its response. Dynamodb requires floats to be provided as `Decimal`. The reverse can also occur if you call `get_thread` from anywhere in code, as `Decimal` is not JSON serializable.

The issue can be seen here #1116 

I have added two new functions within `DynamoDBDataLater` that converts floats to decimals and decimals to floats, calling each function from `_update_item` and `get_thread` respectively. This change resolves the TypeErrors.

2024-07-26 01:36 UTC, mayaankvad requested changes
Thank you so much for this catch.

2024-07-26 01:36 UTC, mayaankvad commented on backend/chainlit/data/dynamodb.py
> +        return obj
```suggestion
    def _convert_decimal_to_floats(self, obj):
        if isinstance(obj, list):
            return [self._convert_decimal_to_floats(i) for i in obj]

        if not isinstance(obj, dict):
            return obj

        for key, value in obj.items():
            if isinstance(value, Decimal):
                obj[key] = float(value)
            elif isinstance(value, dict):
                self._convert_decimal_to_floats(value)
            elif isinstance(value, list):
                obj[key] = [self._convert_decimal_to_floats(i) for i in value]

        return obj
```

Employ Guard clauses

2024-07-26 01:36 UTC, mayaankvad commented on backend/chainlit/data/dynamodb.py
> +        return obj
```suggestion
    def _convert_floats_to_decimal(self, obj):
        if isinstance(obj, list):
            return [self._convert_floats_to_decimal(i) for i in obj]

        if not isinstance(obj, dict):
            return obj

        for key, value in obj.items():
            if isinstance(value, float):
                obj[key] = Decimal(str(value))
            elif isinstance(value, dict):
                self._convert_floats_to_decimal(value)
            elif isinstance(value, list):
                obj[key] = [self._convert_floats_to_decimal(i) for i in value]

        return obj
```

Employ Guard clauses

2024-07-26 01:36 UTC, mayaankvad commented on backend/chainlit/data/dynamodb.py
> +        thread_items = self._convert_decimal_to_floats(thread_items)
Can we include thse conversions in `_serialize_item` and `_deserialize_item` itself.

2024-07-26 01:36 UTC, mayaankvad commented on backend/chainlit/data/dynamodb.py
> +    def _convert_floats_to_decimal(self, obj):
Can we include thse conversions in `_serialize_item` and `_deserialize_item` itself. This way we do not have to concern ourself with these conversions anywhere else in the code.

2024-07-28 16:14 UTC, mayaankvad commented
Diffs LGTM. Next step is for @willydouhard / @tpatel / team to test and approve.

2024-07-28 16:14 UTC, mayaankvad approved these changes

2024-08-01 12:37 UTC, munday-tech commented
Anything you need from me to progress this @mayaankvad ?

2024-08-02 22:12 UTC, mayaankvad commented
No, I think the changes look good. Now it needs @willydouhard / teams approval

2024-08-06 09:14 UTC, willydouhard commented
Seems like mypy is failing @munday-tech

2024-08-10 13:49 UTC, mayaankvad commented
Are you able to make this fix @munday-tech?

2024-08-12 04:13 UTC, munday-tech commented
Will get it done asap

2024-08-12 10:49 UTC, munday-tech commented
@willydouhard @mayaankvad should be good now.

2024-08-27 14:59 UTC, antoniordz96 commented
Any updates on this one? Looking forward to this being merged

2024-08-29 13:19 UTC, mayaankvad commented
Looks ok to me.

2024-09-02 16:52 UTC, mayaankvad approved these changes

2024-09-09 09:50 UTC, dokterbob requested changes
Thanks!

I'm waiting for @willydouhard  to approve https://github.com/Chainlit/chainlit/pull/1288 and https://github.com/Chainlit/chainlit/pull/1292 so we can start unit testing data layers.

Awaiting that, I'd love to have unit tests, doc strings and (if possible) types on your functions. If you're able to, please merge the aforementioned branches into yours and implement the unit tests for the functions you just implemented. 

Thanks!

2024-09-09 09:50 UTC, dokterbob commented on backend/chainlit/data/dynamodb.py
> +    def _convert_floats_to_decimal(self, obj):
And a docstring, if possible.

2024-09-09 09:50 UTC, dokterbob commented on backend/chainlit/data/dynamodb.py
> +    def _convert_decimal_to_floats(self, obj):
And a docstring, if possible.

2024-09-26 12:55 UTC, karthikvarmak1 commented
I am waiting for this one to be merged

2024-10-30 17:20 UTC, liv-watson commented
Also waiting on this to be merged - would someone be able to add the type hints and doc strings so it can be done soon please?

2024-11-19 21:51 UTC, nestorcolt commented
any news about this?

2024-12-06 14:51 UTC, thiagotps commented
Also needing this to be merged.

2025-01-24 06:18 UTC, closed without merging