Adding CHAINLIT_APP_ROOT to modify APP_ROOT
Chainlit/chainlit pull request #1259
Opened 2024-08-25 04:53 UTC by MervinPraison

Adding CHAINLIT_APP_ROOT to modify APP_ROOT

* This is vital. When deploying, it can rely on a centralised config files.

2024-08-26 11:31 UTC, dokterbob commented
Thanks Mervin, code looks good to me. Any chance you could add it to the unreleased section in the changelog, so other uses will be privy of this as well? https://github.com/Chainlit/chainlit/blob/main/CHANGELOG.md#changed

2024-08-26 14:43 UTC, dokterbob requested changes
Thanks Mervin, code looks good to me.

Any chance you could add it to the unreleased section in the changelog, so other uses will be privy of this as well? 

https://github.com/Chainlit/chainlit/blob/main/CHANGELOG.md#changed

2024-08-26 14:45 UTC, dokterbob commented
Ref: https://github.com/Chainlit/docs/issues/170

2024-08-26 16:32 UTC, MervinPraison commented
> Thanks Mervin, code looks good to me.
> 
> Any chance you could add it to the unreleased section in the changelog, so other uses will be privy of this as well?
> 
> https://github.com/Chainlit/chainlit/blob/main/CHANGELOG.md#changed

@dokterbob  Completed ✅

2024-08-26 16:36 UTC, MervinPraison reviewed
Completed ✅ 
Added in unreleased Changelog.md file

2024-08-26 16:41 UTC, MervinPraison reviewed
Reviewed

2024-08-27 09:48 UTC, dokterbob approved these changes
Let's gooooo! 🚀

2024-08-27 10:05 UTC, MervinPraison commented
Thank you 👍 
@dokterbob When do you think this version will get released?

2024-08-27 10:32 UTC, merged

2024-08-27 10:34 UTC, dokterbob commented
@MervinPraison Realistically, we should wait for @willydouhard to come back from holidays -- in a week or so.

Once I know how to roll releases, expect a more regular release cycle.

2024-09-04 08:16 UTC, MervinPraison commented
@willydouhard Waiting for the next release. Thank you