solving issue #1355 - Mixed dependencies in the Storage Clients module for the Data Layer
Chainlit/chainlit pull request #1363
Opened 2024-09-21 09:56 UTC by ndricca

PR to handle issue #1355 

I have added also a pytest for S3StorageClient and moto to mock aws connection. I am not so experienced with Azure so I did not add a test on it.

2024-09-21 11:34 UTC, hadarsharon commented
Thanks for implementing this @ndricca 🥇

2024-09-21 11:52 UTC, ndricca commented
i noticed that @dokterbob said "I imagine `storage_clients` module in the data module with a `base.py` and files for each implementation" while I was still using the  `base.py` from parent folder, so i splitted also this script moving the base method into `storage_clients` submodule

2024-09-21 14:02 UTC, dokterbob commented
Can't wait to review this (prolly around Wednesday in the coming week), unless @willydouhard beats me to it!

2024-09-21 23:21 UTC, gsornsen commented
Oh, nice! Looking forward to trying this out and dropping the need for a supervisor to start up moto-server and create a local s3 bucket in my current implementation.

2024-09-23 11:36 UTC, dokterbob commented
> @dokterbob am i suppose to push also the poetry.lock file? I see fails refer to this. I ran all poetry tests in local and they worked

We use the lockfile to make sure we're all dev'ing in exactly the same environment, creating more reproducible results.

2024-09-23 13:27 UTC, ndricca commented
> > @dokterbob am i suppose to push also the poetry.lock file? I see fails refer to this. I ran all poetry tests in local and they worked
> 
> We use the lockfile to make sure we're all dev'ing in exactly the same environment, creating more reproducible results.

I have merged incoming commits from main and pushed poetry.lock, now it should work

2024-09-24 13:40 UTC, dokterbob commented on backend/tests/data/test_s3_storage_client.py
Please, follow the same import path pattern in test layout. So `/data/storage_clients/test_s3.py`.

2024-09-24 13:41 UTC, dokterbob commented on backend/tests/data/test_sql_alchemy.py
It doesn't seem changes to this file are relevant to this PR. Things like these can easily create merge conflicts! 

Please `git checkout main -- backend/tests/data/test_sql_alchemy.py` this one. :)

2024-09-25 14:46 UTC, ndricca commented on backend/tests/data/test_sql_alchemy.py
i did this, than changed other things and pushed but i see that this file is still here 🤔

2024-09-30 09:21 UTC, ndricca commented on backend/tests/data/test_sql_alchemy.py
no, can you please tell me what do you want me to do? a git revert to exclude it? please tell me the proper commands, i don't want to make noise in the repo.

moreover, i have also updated `cypress/e2e/custom_data_layer/sql_alchemy.py` since it uses the `AzureStorageClient,` it that ok or not?

2024-09-30 09:22 UTC, ndricca commented on backend/tests/data/test_sql_alchemy.py
no, can you please tell me what do you want me to do? a git revert to exclude it? please tell me the proper commands, i don't want to make noise in the repo.

moreover, i have also updated `cypress/e2e/custom_data_layer/sql_alchemy.py` since it uses the `AzureStorageClient`, is that ok or not?

2024-10-10 10:48 UTC, ndricca commented
@dokterbob have you had any chance to read my last comments? Can you tell me what exactly do you want me to do about git commits and how to proceed so that we can close this issue?

2024-10-11 12:57 UTC, dokterbob requested changes
Sorry for the delay. Please see my specific instructions and resolve merge conflicts.

The conflict in `poetry.lock`, you can resolve by (removing other conflicts in the file and) removing the last `content-hash` line altogether. Then, run:
`poetry lock --no-update`

That will regenerate the content-hash and you can `git add poetry.lock`.

Let me know if you get stuck, happy to support! :)

2024-10-11 12:57 UTC, dokterbob commented on backend/tests/data/test_s3_storage_client.py
`git mv backend/tests/data/test_s3_storage_client.py backend/tests/data/test_s3.py` then rolling a commit will do it!

2024-10-11 12:57 UTC, dokterbob commented on backend/tests/data/test_sql_alchemy.py
Forgive my confusion, the `git mv` comment was meant for the other one above (where I spelled it out).

Here, you can reset the file to the original state with `git checkout origin/main -- backend/tests/data/test_sql_alchemy.py`.

2024-10-14 11:06 UTC, dokterbob approved these changes

2024-10-14 11:41 UTC, merged