Improve element type inference
Chainlit/chainlit pull request #209
Opened 2023-07-21 12:29 UTC by MathiasSpanhove

I made some changes to the `element.ts` to make typescript smarter causing less `as` casts. 
I also separated Avatar and TaskList from the other elements so that you don't need to write logic to extract them from the other elements.

Open to any feedback!

2023-07-21 13:51 UTC, willydouhard commented
LGTM, @tpatel could you review also?

2023-07-21 15:33 UTC, tpatel commented
I love that you've moved the Avatar and Tasklist states outside of the element state ❤️ 

Can you share why you've moved the optional url from the `TElement` to each element?

2023-07-21 16:00 UTC, MathiasSpanhove commented
> I love that you've moved the Avatar and Tasklist states outside of the element state ❤️
> 
> Can you share why you've moved the optional url from the `TElement` to each element?

I originally did that because I added Input Widget elements (see PoC PR) that didn't have a url property. Right now you can probably put it back into the base class but I imagine that in the future elements will arrive again that don't have a url.

2023-07-24 08:19 UTC, tpatel requested changes
Thanks for sharing your explanation! Could you move the url back into the element?
The reason is that at the moment, we are setting a url when we persist an element: https://github.com/Chainlit/chainlit/blob/ba72a06ac733dda65de19a5212d262dfbbff4f30/src/chainlit/element.py#L86
So all elements become files with a url, and you use the element url when viewing a conversation in the `history` tab.

2023-07-24 20:49 UTC, MathiasSpanhove commented
> Thanks for sharing your explanation! Could you move the url back into the element? The reason is that at the moment, we are setting a url when we persist an element:
> 
> https://github.com/Chainlit/chainlit/blob/ba72a06ac733dda65de19a5212d262dfbbff4f30/src/chainlit/element.py#L86
> 
> So all elements become files with a url, and you use the element url when viewing a conversation in the `history` tab.

I've added url back into the element.

2023-07-26 13:31 UTC, tpatel approved these changes
✨✨✨ AWESOME ✨✨✨

Thanks for your contribution!

Note: One side effect of these changes is that you can't have a link (from a message) to a tasklist element anymore, and this is an improvement 👍

2023-07-26 13:31 UTC, merged