WIP
Chainlit/chainlit pull request #252
Opened 2023-08-03 13:10 UTC by alimtunc

This PR consist to reduce the time on pre-commit, since we only need to lint/format staged files, its useless to run it on all files when we cant to commit. 

Had some issues with `tsc` actually, I will look at this ASAP

2023-08-06 13:54 UTC, willydouhard requested changes

2023-08-06 13:54 UTC, willydouhard commented on src/chainlit/frontend/src/App.tsx
> +          audience: 'chainlit-clod'
Why are we changing the audience parameter? Looks like a typo

2023-08-08 05:04 UTC, willydouhard commented
where does the `lint-staged` command comes from? eslint directly?

2023-08-08 08:47 UTC, alimtunc commented
> where does the `lint-staged` command comes from? eslint directly?

Running with npx will install it on first run, but it should be in the package, my bad. I fix it.

2023-08-09 04:34 UTC, willydouhard approved these changes

2023-08-09 07:29 UTC, merged