At/remove useless useeffect
Chainlit/chainlit pull request #270
Opened 2023-08-10 16:09 UTC by alimtunc

This PR consist to remove useless useEffects wich can leads to bugs or useless re-renders.

Good to read : https://react.dev/learn/you-might-not-need-an-effect

2023-08-16 10:00 UTC, tpatel reviewed
A couple of comments

2023-08-16 12:22 UTC, alimtunc commented on src/chainlit/frontend/src/components/atoms/element/view.tsx
> +        .then((res) => (element = res))
Yes, that's a good point.

2023-08-16 12:32 UTC, alimtunc commented on src/chainlit/frontend/src/components/organisms/chat/message/message.tsx
> +                  expandAll: false
You're right. I wanted to fix another side effect I had, but I should not reset it on on click detail.

2023-08-17 11:45 UTC, tpatel commented on src/chainlit/frontend/src/components/organisms/chat/message/message.tsx
You might want to revert the changes on this file:

- `setAppSettings` isn't used
- `setShowDetails` doesn't get updated when changing the settings (the settings are in a modal so it would make sense to update the state right away)
<img width="432" alt="image" src="https://github.com/Chainlit/chainlit/assets/494686/9c1e42c1-7097-41aa-a3a8-261e28f3e6a7">

2023-08-17 11:45 UTC, tpatel requested changes
just one more comment 😇

2023-08-17 13:08 UTC, alimtunc commented on src/chainlit/frontend/src/components/organisms/chat/message/message.tsx
Ok I finally revert it, kind of annoying to get the actual state. But these settings shouldn't be persistant ?

2023-08-17 14:21 UTC, tpatel commented on src/chainlit/frontend/src/components/organisms/chat/message/message.tsx
I think the settings are persistent. They can be changed while showing messages thought, so it's better if the user sees the change right away.

2023-08-17 14:21 UTC, tpatel approved these changes
✨✨✨ AWESOME ✨✨✨

2023-08-18 08:41 UTC, alimtunc commented on src/chainlit/frontend/src/components/organisms/chat/message/message.tsx
Nop, they're not, if you refresh the page, this will be reset..

2023-08-18 08:42 UTC, merged

2023-08-18 08:48 UTC, tpatel commented on src/chainlit/frontend/src/components/organisms/chat/message/message.tsx
This might be a bug, only the last setting is saved. I'll ask around for more context on these settings.