Adds support for Okta OAuth provider
Chainlit/chainlit pull request #401
Opened 2023-09-15 12:55 UTC by stian-a-johansen

This PR aims to add support for Okta based logins to chainlit. to use the OktaOauthProvider class set the following environment variables:
OAUTH_OKTA_CLIENT_ID
OAUTH_OKTA_CLIENT_SECRET
OAUTH_OKTA_DOMAIN

2023-09-15 13:01 UTC, willydouhard commented on backend/chainlit/oauth_providers.py
> +    authorize_url = f"https://{os.environ.get('OAUTH_OKTA_DOMAIN')}/oauth2/default/v1/authorize"
maybe check trailing slash?

2023-09-15 13:02 UTC, willydouhard commented on backend/chainlit/oauth_providers.py
> +                f"https://{os.environ.get('OAUTH_OKTA_DOMAIN')}/oauth2/default/v1/userinfo",
same comment for trailing slash

2023-09-15 13:04 UTC, willydouhard commented
This is really cool! I think we probably need to add the Okta provider in the [UI](https://github.com/Chainlit/chainlit/blob/main/libs/components/src/auth/ProviderButton.tsx) also. Looks promising!

2023-09-15 15:23 UTC, willydouhard commented
Awesome, I think we should add okta to the [provider literal](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/types.py#L89).

If this is working locally I would also love to see a screen recording!

2023-09-16 09:46 UTC, willydouhard commented
> > Awesome, I think we should add okta to the [provider literal](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/types.py#L89).
> > If this is working locally I would also love to see a screen recording!
> > Once merged we should also add it to the [documentation](https://docs.chainlit.io/authentication/oauth).
> 
> Great stuff, thanks for the help @willydouhard! I have added the provider literal. Right now our okta isn't set up to allow the callback url directly to the chainlit app, so will have to wait until next week for it to be approved, but will send over a video then 👍 Right now it ends in a callback error on the Okta side when using the button.

Awesome, this looks promising!

2023-09-19 09:23 UTC, willydouhard commented
Any update @stian-a-johansen ?

2023-09-19 10:20 UTC, stian-a-johansen commented
> Any update @stian-a-johansen ?

Hey Willy, it took a while to get the settings updated on the okta side, but here's a video: Apologies for the vibrating black box at the top!


https://github.com/Chainlit/chainlit/assets/9048717/12b466ff-e488-4715-a020-992ca61c9bbc

2023-09-19 11:51 UTC, willydouhard commented
It looks great! Are we missing anything or should we do a last review to merge?

2023-09-19 12:14 UTC, stian-a-johansen commented
As far as I see I think it's just docs that's missing now @willydouhard 👍  Thank you!

2023-09-19 16:47 UTC, willydouhard commented
the `""` is breaking because it is [inside a f string](https://github.com/Serendipity-AI/chainlit/blob/SJ/okta_provider/backend/chainlit/oauth_providers.py#L196). Almost there!

2023-09-19 17:23 UTC, stian-a-johansen commented
> the `""` is breaking because it is [inside a f string](https://github.com/Serendipity-AI/chainlit/blob/SJ/okta_provider/backend/chainlit/oauth_providers.py#L196). Almost there!

🤦 now it's better!

2023-09-20 13:46 UTC, stian-a-johansen commented
> CI is green! I am not able to test it myself, you confirm everything works on your end?

Yep! Logs in and works here 👍  Very nice the ability to support these!

2023-09-20 13:48 UTC, stian-a-johansen commented
Hm, looks like the literals have been removed from types.py in another merge, trying to see where it should go now

2023-09-20 13:49 UTC, willydouhard commented
> Hm, looks like the literals have been removed from types.py in another merge, trying to see where it should go now

Yes, I just merged another PR. It goes in client/base.py.

2023-09-20 15:16 UTC, willydouhard commented
Looks good! Going to merge. If you can add a paragraph [here](https://docs.chainlit.io/authentication/oauth) with a code example it would be awesome!

2023-09-20 16:00 UTC, stian-a-johansen commented
Just merged in the latest from `main` into this branch

2023-09-20 22:04 UTC, willydouhard requested changes

2023-09-20 22:04 UTC, willydouhard commented on libs/components/src/auth/ProviderButton.tsx
> +import Okta from './Okta.tsx';
The icon is exported as a const and not default. Either change this line to `import {Okta} from ...` or export the icon as default

2023-09-20 22:05 UTC, willydouhard commented on libs/components/src/auth/ProviderButton.tsx
> +import Okta from './Okta.tsx';
This makes the build of libs/components fail

2023-09-21 17:36 UTC, willydouhard approved these changes

2023-09-21 17:36 UTC, willydouhard commented
Approved! Thank you for your work 🎉

2023-09-21 17:37 UTC, merged

2023-09-22 09:49 UTC, stian-a-johansen commented
> Approved! Thank you for your work 🎉

Thanks for the merge and the help!