feat: add chat profiles
Chainlit/chainlit pull request #465
Opened 2023-10-10 14:06 UTC by tpatel

- Chat profiles enable the end user to select a pre-configuration before starting a chat
- Chat profiles can be declared with a function decorated by `@cl.chat_profiles`
- Chat profiles are sent to the client via the `/project/settings` endpoint
- Users can select their chat profile of choice before starting a conversation (first or new conversation)
- The chat profile is sent to the backend with the websocket connect as a header
- The selected chat profile is stored in the user session as "chat_profile"

## TODO

- [ ] discuss design & implement
- [ ] add markdown description
- [ ] tackle the 1 chat profile edge case

2023-10-11 12:00 UTC, willydouhard requested changes

2023-10-11 12:24 UTC, tpatel commented on frontend/src/components/molecules/newChatButton.tsx
> +  const setChatProfile = useSetRecoilState(chatProfile);
Nice catch! Fixed ✅

2023-10-11 12:34 UTC, tpatel commented on backend/chainlit/__init__.py
> +def chat_profiles(
yes!

2023-10-11 12:38 UTC, tpatel commented on backend/chainlit/types.py
> +    description: str
not a fan of the long name, but it will help users understand the capabilities of the field without looking at the docs 👍

2023-10-13 08:14 UTC, willydouhard approved these changes

2023-10-13 08:15 UTC, merged