Add config.ui.meta_image
Chainlit/chainlit pull request #757
Opened 2024-02-21 11:20 UTC by MarkEdmondson1234

This lets you set the meta_image that appears when sharing your Chainlit app, by default it is https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png but by adding to your config your own banner you can use your own.

e.g. within `.chainlit/config.toml`

```toml

[UI]
# Name of the app and chatbot.
name = "Your app name"

# the metadata image that appears when sharing links
meta_image = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

```

2024-03-07 11:40 UTC, tpatel requested changes
Thanks for your contribution ✨ 

Could you add a this `image` setting in a new `config.ui.meta` category in the [configuration](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/config.py)?

2024-03-18 06:24 UTC, MarkEdmondson1234 commented
@tpatel I have updated the config as requested

2024-04-02 08:20 UTC, tpatel commented
Thanks for the update @MarkEdmondson1234, sorry I wasn't clear on all the things that needs to be updated. Here are some example from another PR:
- You would need to create a python class for the meta object, and add it into the `UISettings` class, like in this PR: https://github.com/Chainlit/chainlit/pull/787/files#diff-e76edd7e411b9e044dbc1f307015efc5d8e83f7b254af919786191f86dfc7c74R192-R199
- You would also need to update the frontend types to make sure they match the backend types, like in this PR: https://github.com/Chainlit/chainlit/pull/787/files#diff-e8a4293b0716fc7dcef3122181e5d41b58a52c46d779d352953bd0d41db43261R24-R29

2024-04-22 10:26 UTC, tpatel commented
Closing as the discussion has stopped, we can still reopen the PR in the future

2024-04-22 10:26 UTC, closed without merging