Update thread list on first interaction
Chainlit/chainlit pull request #923
Opened 2024-04-18 15:29 UTC by tpatel

- re-fetch the thread list on first interaction
- navigate to /thread/:id url when creating a new conversation
- update the /thread/:id page to allow for displaying the current chat
- add `threadId` to `useChatMessages` to get the current conversation thread id
- update "back to conversation" links
- clear current conversation when deleting the current thread

based on the work from @BrittleFoot in https://github.com/Chainlit/chainlit/pull/838

2024-04-19 05:31 UTC, willydouhard commented
Nice work! Seems to fail on chat profiles though:

```py
import chainlit as cl

@cl.password_auth_callback
def auth():
    return cl.User(identifier="test")


@cl.set_chat_profiles
async def chat_profile():
    return [
        cl.ChatProfile(
            name="GPT-3.5",
            markdown_description="The underlying LLM model is **GPT-3.5**.",
            icon="https://picsum.photos/200",
        ),
        cl.ChatProfile(
            name="GPT-4",
            markdown_description="The underlying LLM model is **GPT-4**.",
            icon="https://picsum.photos/250",
        ),
    ]

@cl.on_chat_start
async def on_chat_start():
    chat_profile = cl.user_session.get("chat_profile")
    await cl.Message(
        content=f"starting chat using the {chat_profile} chat profile"
    ).send()
```

2024-04-23 09:20 UTC, willydouhard requested changes

2024-04-23 09:21 UTC, tpatel commented on backend/chainlit/emitter.py
> +                asyncio.create_task(
good catch, fixing it now

2024-04-23 14:26 UTC, willydouhard commented on cypress/e2e/data_layer/spec.cy.ts
>    // Thread name should be renamed with first interaction
this comment is not relevant anymore

2024-04-23 14:44 UTC, willydouhard approved these changes

2024-04-23 14:48 UTC, merged