feat: add ssl support using custom key/cert files
Chainlit/chainlit pull request #933
Opened 2024-04-23 17:21 UTC by dahifi

Someone on the discord asked for a way to run the app behind https, so I added a run config parameters to accept keyfile and cert paths, and pass them to uvicorn. 

I was unable to run commit hooks on this, nor did I test, but putting this here to see if anyone can validate or pick it up from here.

2024-04-27 20:36 UTC, puppetm4st3r commented
if I add those changes to my local, I it will work? or is incomplete ? the added parameters must be provided as environment vars or running paremeters in chainlit executable ?

Best regards!

2024-04-30 12:46 UTC, puppetm4st3r commented
in my case the reverse proxy + chainlit + serving wasm artifacts didnt liked it to iOS devices, so I have solved appliying this PR and removing the prody and works fine.... and its a clearer solution for lite infrastructure use cases.

2024-05-06 17:22 UTC, veeragoni commented
localhost

2024-05-06 17:23 UTC, veeragoni commented
> Thanks for your PR, there is a similar one here: #905
> 
> Do you have more background as to why folks who want to create a publicly accessible Chainlit instance without having a proxy in front of it?

localhost

2024-05-23 13:04 UTC, tpatel requested changes
Looks good, could you add the `CHAINLIT_` prefix to env variables?
I've tried to do it myself but I don't have the rights on your fork.

2024-05-23 13:04 UTC, tpatel commented on backend/chainlit/cli/__init__.py
> +    ssl_keyfile = os.environ.get("SSL_KEY", None)
```suggestion
    ssl_certfile = os.environ.get("CHAINLIT_SSL_CERT", None)
    ssl_keyfile = os.environ.get("CHAINLIT_SSL_KEY", None)
```

2024-05-23 13:04 UTC, tpatel commented on backend/chainlit/cli/__init__.py
> +    envvar="SSL_CERT",
```suggestion
    envvar="CHAINLIT_SSL_CERT",
```

2024-05-23 13:04 UTC, tpatel commented on backend/chainlit/cli/__init__.py
> +    envvar="SSL_KEY",
```suggestion
    envvar="CHAINLIT_SSL_KEY",
```

2024-05-23 13:04 UTC, tpatel commented on backend/chainlit/cli/__init__.py
> +        os.environ["SSL_KEY"] = ssl_key
```suggestion
        os.environ["CHAINLIT_SSL_CERT"] = ssl_cert
        os.environ["CHAINLIT_SSL_KEY"] = ssl_key
```

2024-05-28 08:15 UTC, tpatel requested changes
There are two remaining suggestions that needs to be committed for me to merge this PR.

2024-05-30 12:33 UTC, yiouyou commented
@tpatel This merge is quite useful when running the voice feature of chainlit. Could you check if it's ready to merge? If there's a simple document of --ssl-cert etc on the repo main page, that would be very useful.

Thanks!

2024-05-31 09:32 UTC, tpatel commented
closing in favor of https://github.com/Chainlit/chainlit/pull/1047 (I've made the change there).

2024-05-31 09:32 UTC, closed without merging